title: Joe Juzl
email: joejuzl@gmail.com
description: >
  Joe Juzl's personal site.
baseurl: ""
url: ""
github_username:  joejuzl
google_analytics: UA-104089015-1

# Build settings
markdown: kramdown
plugins:
  - jekyll-titleize
